export const LOAD_REQ_CARDS_REQUEST = 'LOAD_REQ_CARDS_REQUEST';
export const LOAD_REQ_CARDS_SUCCESS = 'LOAD_REQ_CARDS_SUCCESS';
export const LOAD_REQ_CARDS_FAILURE = 'LOAD_REQ_CARDS_FAILURE';

export const SELECTED_MATERIAL = 'SELECTED_MATERIAL';
export const DESELECTED_MATERIAL = 'DESELECTED_MATERIAL';

export const SELECTED_METHOD = 'SELECTED_METHOD';
export const DESELECTED_METHOD = 'DESELECTED_METHOD';

export const TOGGLE_STATUS = 'TOGGLE_STATUS';
